routes/web.php
<?php

use App\Http\Controllers\AcercadeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ServicioController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\ProyectoController;
use App\Http\Controllers\EquipoController;
use App\Http\Controllers\PortadaController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require __DIR__.'/auth.php';

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth','verified'])->name('dashboard');


//Controlladores para Admin
Route::prefix('/administrador')->group(function (){
    Route::resource('/panel', AdminController::class);
    Route::resource('/servicios', ServicioController::class)->names('servicio');
    Route::resource('/proyectos', ProyectoController::class)->names('proyecto');
    Route::resource('/equipo', EquipoController::class)->names('equipo');
    Route::resource('/portada', PortadaController::class)->names('portada');
    Route::resource('/acercade', AcercadeController::class)->names('acercade');
});


//Controlladores para Cliente
/*
Route::prefix('/')->group(function (){
    Route::resource('/servicios', ClienteController::class);
});
*/

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard.blade.php
 

<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Servicios
        </h2>
    </x-slot>

   
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>