routes/web.php
<?php

use App\Http\Controllers\AcercadeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ServicioController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\ProyectoController;
use App\Http\Controllers\EquipoController;
use App\Http\Controllers\PortadaController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require __DIR__.'/auth.php';

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth','verified'])->name('dashboard');


//Controlladores para Admin
Route::prefix('/administrador')->group(function (){
    Route::resource('/panel', AdminController::class);
    Route::resource('/servicios', ServicioController::class)->names('servicio');
    Route::resource('/proyectos', ProyectoController::class)->names('proyecto');
    Route::resource('/equipo', EquipoController::class)->names('equipo');
    Route::resource('/portada', PortadaController::class)->names('portada');
    Route::resource('/acercade', AcercadeController::class)->names('acercade');
});


//Controlladores para Cliente
/*
Route::prefix('/')->group(function (){
    Route::resource('/servicios', ClienteController::class);
});
*/

app/Models/Acercade.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Acercade extends Model
{
    use HasFactory;
    protected $table = 'acercades';

    protected $fillable = [
        'acercade',
        'foto1',
        'mision',
        'foto2',
        'vision',
        'foto3',
        'valores',
        'foto4',

    ];
}

app/Http/Controllers/AcercadeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Acercade;
use Illuminate\Http\Request;
use Image;
use Illuminate\Support\Facades\Validator;

class AcercadeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
        public function __construct()
    {
        $this->middleware(['auth','verified']);
        $this->middleware('soloadmin',['only'=>'index' ]);

    }
    public function index()
    {

        $acercade = Acercade::all();
        return view('admin/acercade/index',compact('acercade'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Acercade  $acercade
     * @return \Illuminate\Http\Response
     */
    public function show(Acercade $acercade)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Acercade  $acercade
     * @return \Illuminate\Http\Response
     */
    public function edit(Acercade $acercade)
    {
        return view('admin/acercade/editar', compact('acercade'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Acercade  $acercade
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Acercade $acercade)
    {
        $validator = Validator::make($request->all(), [

            'acercade'   => 'required|min:50|max:500',
            'f_acercade'   => '|file|max:2024|mimes:jpeg,bmp,png,jpg',
            'mision'   => 'required|min:50|max:500',
            'f_mision'  => '|file|max:2024|mimes:jpeg,bmp,png,jpg',
            'vision'   => 'required|min:50|max:500',
            'f_vision'  => '|file|max:2024|mimes:jpeg,bmp,png,jpg',
            'valores'   => 'required|min:50|max:500',
            'f_valores'  => '|file|max:2024|mimes:jpeg,bmp,png,jpg',
        ]);

        $f_acercade = "";
        $f_mision = "";
        $f_vision = "";
        $f_valores = "";

        if ($validator->fails()) {
            $errors = $validator->errors();
        return redirect()->back()->withErrors($errors);
        } else
        {
            if ($request->hasfile('f_acercade')) {
                $avatar = $request->file('f_acercade');
                $filename = '1' . '.' . $avatar->getClientOriginalExtension();
                Image::make($avatar)->resize(200, 200)->save(public_path('/theme/assets/img/about/' . $filename));
                $f_acercade= 'theme\assets\img\about\\' . $filename;
            } else {
                $f_acercade = $acercade->foto1;
            }


            if ($request->hasfile('f_mision')) {
                $avatar = $request->file('f_mision');
                $filename = '2' . '.' . $avatar->getClientOriginalExtension();
                Image::make($avatar)->resize(200, 200)->save(public_path('/theme/assets/img/about/' . $filename));
                $f_mision= 'theme\assets\img\about\\' . $filename;
            } else {
                $f_mision = $acercade->foto2;
            }

            if ($request->hasfile('f_vision')) {
                $avatar = $request->file('f_vision');
                $filename = '3' . '.' . $avatar->getClientOriginalExtension();
                Image::make($avatar)->resize(200, 200)->save(public_path('/theme/assets/img/about/' . $filename));
                $f_vision= 'theme\assets\img\about\\' . $filename;
            } else {
                $f_vision = $acercade->foto3;
            }

            if ($request->hasfile('f_valores')) {
                $avatar = $request->file('f_valores');
                $filename = '4' . '.' . $avatar->getClientOriginalExtension();
                Image::make($avatar)->resize(200, 200)->save(public_path('/theme/assets/img/about/' . $filename));
                $f_valores= 'theme\assets\img\about\\' . $filename;
            } else {
                $f_valores = $acercade->foto4;
            }

            //Actualizar
            $acercade->update([
                'acercade' => $request->input('acercade'),
                'foto1' =>$f_acercade,
                'mision' => $request->input('mision'),
                'foto2' =>$f_mision,
                'vision' => $request->input('vision'),
                'foto3' =>$f_vision,
                'valores' => $request->input('valores'),
                'foto4' =>$f_valores,
            ]);

        }
        return redirect()->route('acercade.index')
        ->with('status_success','Acerca de actualizado con éxito ');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Acercade  $acercade
     * @return \Illuminate\Http\Response
     */
    public function destroy(Acercade $acercade)
    {
        //
    }
}

resources/views/admin/acercade/editar.blade.php
@extends('adminlte::page')
@section('title', 'Multiservicios - Acercade')

@section('plugins.Sweetalert2', true)
@section('content_header')

@stop

@section('content')

    <div class="card">
        <div class="card-header">
            <h1 class="card-title">Multiservicios - Editar</h1>

        </div>
        <div class="card-body">
            @include('custom.message')
            <form action="{{ route('acercade.update', $acercade->id) }}" method="POST" enctype="multipart/form-data">
                @method('Put')
                @csrf
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Acercade</th>
                            <th scope="col">imagen</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <textarea id="acercade" name="acercade" rows="5" cols="50"> {{ $acercade->acercade }}
      </textarea>
                            </td>
                            <td> <img src="{{ asset($acercade->foto1) }}" width="100" height="100">
                                <input class="form-control" accept="image/png,image/jpeg" type="file" name="f_acercade" id="f_acercade">
                            </td>
                        </tr>

                        <tr>

                            <th scope="col">Misión</th>
                            <th scope="col">imagen</th>
                        </tr>
                        <tr>
                            <td>
                                <textarea id="mision" name="mision" rows="5" cols="50"> {{ $acercade->mision }}
      </textarea>
                            </td>
                            <td> <img src="{{ asset($acercade->foto2) }}" width="100" height="100">
                                <input class="form-control" accept="image/png,image/jpeg" type="file" name="f_mision" id="f_mision">
                            </td>
                        </tr>

                        <tr>
                            <th scope="col">Visón</th>
                            <th scope="col">imagen</th>

                        </tr>

                        <tr>
                            <td>
                                <textarea id="vision" name="vision" rows="5" cols="50"> {{ $acercade->vision }}
      </textarea>
                            </td>
                            <td> <img src="{{ asset($acercade->foto3) }}" width="100" height="100">
                                <input class="form-control" accept="image/png,image/jpeg" type="file" name="f_vision" id="f_vision">
                            </td>
                        </tr>

                        <tr>
                            <th scope="col">Valores</th>
                            <th scope="col">imagen</th>
                        </tr>
                        <tr>

                            <td>
                                <textarea id="valores" name="valores" rows="5" cols="50"> {{ $acercade->valores }}
</textarea>
                            </td>
                            <td> <img src="{{ asset($acercade->foto4) }}" width="100" height="100">
                                <input class="form-control" accept="image/png,image/jpeg" type="file" name="f_valores" id="f_valores">
                            </td>

                        </tr>



                    </tbody>
                </table>
                <center><input class="btn btn-success" type="submit" value="Guardar"> </center>
            </form>

        </div>



    </div>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <!--
        <script>
            Swal.fire(
                'Good job!',
                'You clicked the button!',
                'success'
            )
        </script>
        -->
@stop

resources/views/admin/acercade/index.blade.php
@extends('adminlte::page')
@section('title', 'Multiservicios - Acercade')

@section('plugins.Sweetalert2', true)
@section('content_header')

@stop

@section('content')

<div class="card">
    <div class="card-header">
    <h1 class="card-title">Multiservicios - Acerca de</h1>

    </div>
    <div class="card-body">
        @include('custom.message')

    <h2>Acerca de </h2>

    <table class="table">
        <thead>
          <tr>
            <th scope="col">Acercade</th>
            <th scope="col">imagen</th>
            <th scope="col">Misión</th>
            <th scope="col">imagen</th>



        </thead>
        <tbody>

            @foreach ($acercade as $acer )
          <tr>
            <td>{{ $acer->acercade }}</td>
            <td> <img src="{{ asset($acer->foto1) }}" width="100" height="100"></td>
            <td>{{ $acer->mision }}</td>
            <td> <img src="{{ asset($acer->foto2) }}" width="100" height="100"></td>
        </tr>

        <tr>
            <th scope="col">Visón</th>
            <th scope="col">imagen</th>
            <th scope="col">Valores</th>
            <th scope="col">imagen</th>
        </tr>

        <tr>
            <td>{{ $acer->vision }}</td>
            <td> <img src="{{ asset($acer->foto3) }}" width="100" height="100"></td>
            <td>{{ $acer->valores }}</td>
            <td> <img src="{{ asset($acer->foto4) }}" width="100" height="100"></td>
        </tr>


          @endforeach


        </tbody>
      </table>


    </div>

    <center><a class="btn btn-success" href="{{ route('acercade.edit', $acer->id) }}">Editar</a></center>

</div>

@stop

@section('css')
	<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<!--
<script>
Swal.fire(
  'Good job!',
  'You clicked the button!',
  'success'
)
</script>
-->
@stop