routes/web.php
<?php

use App\Http\Controllers\AcercadeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ServicioController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\ProyectoController;
use App\Http\Controllers\EquipoController;
use App\Http\Controllers\PortadaController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require __DIR__.'/auth.php';

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth','verified'])->name('dashboard');


//Controlladores para Admin
Route::prefix('/administrador')->group(function (){
    Route::resource('/panel', AdminController::class);
    Route::resource('/servicios', ServicioController::class)->names('servicio');
    Route::resource('/proyectos', ProyectoController::class)->names('proyecto');
    Route::resource('/equipo', EquipoController::class)->names('equipo');
    Route::resource('/portada', PortadaController::class)->names('portada');
    Route::resource('/acercade', AcercadeController::class)->names('acercade');
});


//Controlladores para Cliente
/*
Route::prefix('/')->group(function (){
    Route::resource('/servicios', ClienteController::class);
});
*/

app/Models/Equipo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Equipo extends Model
{
    use HasFactory;
    protected $table = 'equipos';

    protected $fillable = [
        'foto',
        'nombres',
        'habilidad',
        'mensaje',
        'contacto',


    ];
}

app/Http/Controllers/EquipoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Equipo;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Image;
use Illuminate\Support\Facades\Validator;

class EquipoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
        public function __construct()
    {
        $this->middleware(['auth','verified']);
        $this->middleware('soloadmin',['only'=>'index' ]);

    }
    public function index()
    {
        $equipos = Equipo::all();
        return view('admin/equipo/index',compact('equipos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Equipo  $equipo
     * @return \Illuminate\Http\Response
     */
    public function show(Equipo $equipo)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Equipo  $equipo
     * @return \Illuminate\Http\Response
     */
    public function edit(Equipo $equipo)
    {
        return view('admin/equipo/editar', compact('equipo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Equipo  $equipo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Equipo $equipo)
    {
        $validator = Validator::make($request->all(), [
            'foto'   => '|file|max:2024|mimes:jpeg,bmp,png,jpg',
            'nombres'   => 'required|min:5|max:200',
            'habilidad'   => 'required|min:5|max:200',
            'mensaje'   => 'required|min:10|max:200',
            'contacto'   => 'required|min:10|max:200',

        ]);

        if ($validator->fails()) {
            $errors = $validator->errors();
        return redirect()->back()->withErrors($errors);
        } else

        {
            $imagen = "";
            $image_path = "";

            if ($request->hasfile('foto')) {
                $avatar = $request->file('foto');
                $filename = Str::random(5) . '.' . $avatar->getClientOriginalExtension();
                Image::make($avatar)->resize(500, 500)->save(public_path('/theme/assets/img/team/' . $filename));
                $imagen= '/theme/assets/img/team/' . $filename;
                $image_path = public_path().$equipo->foto;
                unlink($image_path);
            } else {
                $imagen = $equipo->foto;
            }


            $equipo->update([
                'foto' => $imagen,
                'nombres' => $request->input('nombres'),
                'habilidad' => $request->input('habilidad'),
                'mensaje' => $request->input('mensaje'),
                'contacto' => $request->input('contacto'),

            ]);


        }
     return redirect()->route('equipo.index')
       ->with('status_success','Equipo actualizado con éxito ');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Equipo  $equipo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Equipo $equipo)
    {
        //
    }
}

resources/views/admin/equipo/editar.blade.php
@extends('adminlte::page')
@section('title', 'Multiservicios - Editar')

@section('plugins.Sweetalert2', true)
@section('content_header')

@stop

@section('content')

<div class="card">
    <div class="card-header">
    <h1 class="card-title">Multiservicios - Editar</h1>
    </div>
    <div class="card-body">
        @include('custom.message')
        <form action="{{ route('equipo.update', $equipo->id) }}" method="POST" enctype="multipart/form-data">
            @method('Put')
            @csrf
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Foto</th>
            <td><img src="{{ asset($equipo->foto) }}" width="100" height="100">
                <input class="form-control"  accept="image/png,image/jpeg" type="file" name="foto" id="foto" >
            </td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </thead>
        <tr>
            <th scope="col">Nombres</th>
            <td><input class="form-control" type="text" name="nombres" id="nombres"
                value="  {{ $equipo->nombres }}"></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>

          </tr>

          <tr>
            <th scope="col">Habilidad</th>
            <td><input class="form-control" type="text" name="habilidad" id="habilidad"
                value="  {{ $equipo->habilidad }}"></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>

          </tr>

          <tr>
            <th scope="col">Mensaje</th>
            <td><input class="form-control" type="text" name="mensaje" id="mensaje"
                value="  {{ $equipo->mensaje }}"></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>

          </tr>

          <tr>
            <th scope="col">Contacto</th>
            <td><input class="form-control" type="text" name="contacto" id="contacto"
                value="  {{ $equipo->contacto }}"></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>

          </tr>
        <tbody>

        </tbody>
      </table>
      <center><input class="btn btn-success" type="submit" value="Guardar"> </center>
    </form>
    </div>


</div>

@stop

@section('css')
	<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<!--
<script>
Swal.fire(
  'Good job!',
  'You clicked the button!',
  'success'
)
</script>
-->
@stop

resources/views/admin/equipo/index.blade.php
@extends('adminlte::page')
@section('title', 'Multiservicios - Equipo')

@section('plugins.Sweetalert2', true)
@section('content_header')

@stop

@section('content')

<div class="card">
    <div class="card-header">
    <h1 class="card-title">Multiservicios - Equipo</h1>
    </div>
    <div class="card-body">
 @include('custom.message')

    <h2>Equipo </h2>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Foto</th>
            <th scope="col">Nombres</th>
            <th scope="col">Habilidad</th>
            <th scope="col">Mensaje</th>
            <th scope="col">Celular</th>
            <th scope="col">Acciones</th>

          </tr>
        </thead>
        <tbody>

  @foreach ($equipos as $equipo )


          <tr>
            <td> <img src="{{ asset($equipo->foto) }}" width="100" height="100"></td>
            <td>{{ $equipo->nombres }}</td>
            <td>{{ $equipo->habilidad }}</td>
            <td>{{ $equipo->mensaje }}</td>
            <td>{{ $equipo->contacto }}</td>
            <td><a class="btn btn-success" href="{{ route('equipo.edit', $equipo->id) }}">Editar</a></td>
          </tr>
          @endforeach


        </tbody>
      </table>
    </div>


</div>

@stop

@section('css')
	<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<!--
<script>
Swal.fire(
  'Good job!',
  'You clicked the button!',
  'success'
)
</script>
-->
@stop